import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import { Nunito } from 'next/font/google';
import ReactQueryProvider from "./libs/tanstackContext";
import { ProviderContext } from "./context/createContext";
import { ToastProvider } from "./context/createToastContext";

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400','500','600','700'], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased relative overflow-x-hidden bg-black text-white`}
      >
      <ProviderContext>
        <ToastProvider>
          <ReactQueryProvider>
            <Header />
            {children}
          </ReactQueryProvider>
        </ToastProvider>
      </ProviderContext>
      </body>
    </html>
  );
}
